server:
  port: 8081

spring:
  application:
    name: mentee-power-crm
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 10000

gg:
  jte:
    templateLocation: classpath:/jte/
    developmentMode: true

email:
  validation:
    base-url: ${EMAIL_VALIDATION_URL:http://localhost:8089}

logging:
  level:
    org.springframework.web: DEBUG
    ru.mentee.power.crm: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html