server:
  port: 8081

spring:
  application:
    name: mentee-power-crm
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

gg:
  jte:
    templateLocation: classpath:/jte/
    developmentMode: true

logging:
  level:
    org.springframework.web: DEBUG
    ru.mentee.power.crm: DEBUG